In [4]:
import cv2, os
import matplotlib

In [6]:
from google.colab import drive
drive.mount('/content/drive')      

Mounted at /content/drive


In [7]:
data_path= '/content/drive/My Drive/DMML2/Mask'

In [8]:
categories = os.listdir(data_path)
labels = [i for i in range(len(categories))]

label_dict = dict(zip(categories, labels))

print(label_dict)
print(categories)
print(labels)

{'Mask': 0, 'No Mask': 1}
['Mask', 'No Mask']
[0, 1]


In [9]:
img_size = 100
data = []
target = []

for category in categories:
  folder_path = os.path.join(data_path, category)
  img_names = os.listdir(folder_path)

  for img_name in img_names:
    img_path = os.path.join(folder_path, img_name)
    img = cv2.imread(img_path)

    try:
     
      resized = cv2.resize(img, (img_size, img_size))           #resizing the images to 100*100 pixels

      data.append(resized)                                                          #appending the images and its labels
      target.append(label_dict[category])

    except Exception as e:
      print('Exception:', e)

In [11]:
import numpy as np

data = np.array(data)/255.0                                                                                    #normalizing the image data
data = np.reshape(data, (data.shape[0], img_size, img_size, 3))                   #reshaping the image data array    
target = np.array(target)                                                                                           

In [12]:
data

array([[[[3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         [3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         [3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         ...,
         [3.36793541e-03, 3.39869281e-03, 3.41407151e-03],
         [3.36793541e-03, 3.39869281e-03, 3.41407151e-03],
         [3.36793541e-03, 3.39869281e-03, 3.41407151e-03]],

        [[3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         [3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         [3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         ...,
         [3.36793541e-03, 3.39869281e-03, 3.41407151e-03],
         [3.36793541e-03, 3.39869281e-03, 3.41407151e-03],
         [3.36793541e-03, 3.39869281e-03, 3.41407151e-03]],

        [[3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         [3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         [3.46020761e-03, 3.49096501e-03, 3.50634371e-03],
         ...,
         [3.36793541e-03, 3.39869281e-03, 3.41407151e-03],
         [

In [13]:
target

array([0, 0, 0, ..., 1, 1, 1])

In [14]:
from keras.utils import np_utils

new_target = np_utils.to_categorical(target)                #converting the label array into categorical values

In [16]:
new_target

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, new_target, test_size = 0.30 )                      #splitting the data

In [19]:
np.save('X_train4', X_train)
np.save('X_test4', X_test)
np.save('y_train4', y_train)
np.save('y_test4', y_test)